---
- name: Install apt dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates

# This is the Debian 12 (bookworm) specific repository configuration
# It uses the deb822_repository module to ensure compatibility with the Debian 12 repository format.
# It is only applied when the distribution is Debian and the release is bookworm.
#  deb822_repository is new in ansible-core 2.15
- name: Configure CernVM apt repository
  ansible.builtin.deb822_repository:
    name: cernvm
    types: [deb]
    uris: "https://cvmrepo.web.cern.ch/cvmrepo/apt"
    suites: "{{ ansible_distribution_release }}-prod"
    components:
      - main
    signed_by: https://cvmrepo.web.cern.ch/cvmrepo/apt/cernvm.gpg
    state: present
    enabled: true
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'bookworm'
 
# Install CernVM-FS packages and dependencies 
- name: Install CernVM-FS packages and dependencies (apt)
  ansible.builtin.apt:
    name: "{{ cvmfs_packages[_cvmfs_role] }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
